### PR TITLE
Inject Controller from Domain

### PR DESCRIPTION
**Pull request by diversemix**
A few things left to do:
- [ ] Finish writing DTO/Entity interface
- [ ] Start using `Option`s

### CODE REVIEW

**Comment by erezmus** [comment]
I'm finding it confusing to have the concept of a controller inside a package. Controller is usually used as a framework level concept that calls code inside the app (in our case packages).

I think it should be the other way round:
`submission-adaptor/submission.service.ts` should be`submission-adaptor/submission.controller.ts`
and `packages/submission/submission.controller.ts` should be called `packages/submission/submission.service.ts`

The SubmissionService should then injected into the Controller, not the other way around.

If we do wish to keep Controller inside the package, we should make it clear that its not your standard framework use interface controller but something that is independent of the framework.

**Comment by diversemix** [comment]
Don't let the name `controller` deceive you ... the idea of the `submission-adaptor` is that its connecting the nestjs framework to the logic of the domain. The `controller` of the domain should remain inside of the domain as that is the implementation. The plumbing should remain as part of the nestjs module.

**Comment by diversemix** [comment]
Another confusion is that we are halfway through the refactor.

**Comment by petereast** [comment]
I'm going to merge this as-is and add the subtasks as followup tickets

**Pull request merged**
